version: '3'
services:

  postgres:
    image: "postgres:14.5"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      # only use that locally or in CI/CD
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: "CheckingTask"

